site_name: Pywedge documentation
nav:
  - Home: index.md
  - Modules: modules.md
  - Examples: examples.md
  - License: license.md

theme: readthedocs
repo_url: https://github.com/taknev83/pywedge
edit_uri: '#root/path/docs/'
repo_name: 'GitHub'
site_description: 'Pywedge - Interactive Machine Learning'
site_author: 'Venkatesh Rengarajan Muthu'
copyright: '&copy; Copyright 2020 - 2021 Venkatesh Rengarajan Muthu'
